### ISSUE TITLE
set directory to utils.py in chapter 09

### ISSUE THREAD

**Issue by Silentstone2** [luispedro/BuildingMachineLearningSystemsWithPython#14]
When I run the utils.py file, the following text appears:
"Please set GENRE_DIR and TEST_DIR in utils.py"

leaving the comment: "Process finished with exit code 1"
and I have no idea what to do and how to do. Help me please!
![image](https://cloud.githubusercontent.com/assets/13782416/13205139/a05cafe6-d906-11e5-9672-39dbf10b08a1.png)

Note: I have sample .wav files in a folder "genres" inside the same directory where my python project exists. That folder further contains subfolders for samples in each music genre

**Comment by wrichert** [comment]
You need to set GENRE_DIR and TEST_DIR to your local versions. For copyright reasons we could not provide the music files with the code. Just put together a bunch of sound files from your local hard drive and then it should work.
