### ISSUE TITLE
cannot import name 'CHART_DIR'

### ISSUE THREAD

**Issue by edvbb** [luispedro/BuildingMachineLearningSystemsWithPython#19]
Good day!
I have a mistake in BuildingMachineLearningSystemsWithPython/ch03/plot_kmeans_example.py

`import utils 
CHART_DIR = 'D:\Python'
from utils import CHART_DIR

ImportError: cannot import name 'CHART_DIR'`

what did i do wrong?

**Comment by luispedro** [comment]
I tried this out and it worked on my machine, but do note that this is a relative import. Thus, you should be running the script *in the BuildingMachineLearningSystemsWithPython/ch03* working directory.

Let me know if it works when you are running it in that working directory:

    cd BuildingMachineLearningSystemsWithPython/ch03
    python plot_kmeans_example.py

**Comment by edvbb** [comment]
Thanks
It works

**Comment by luispedro** [comment]
Great to hear! Closing issue.
