### ISSUE TITLE
Movie features, user features

### ISSUE THREAD

**Issue by edvbb** [luispedro/BuildingMachineLearningSystemsWithPython#20]
Pedro, you use just utility matrix.
Why don't you use movie features, user features?
because the utility matrix gives a more accurate prediction?
or you just looked at an example, without touching movie features, user features?

**Comment by luispedro** [comment]
Hi, I'm not sure I fully understand you. Can you be more explicit about what you are suggesting?

**Comment by touijri** [comment]
Hi Sir,


I m reading with a lot of attention your book that I purchased last year,  and wanted o know if there was an online version of the bookthat  I can use?


Thank you for letting me know,

Best regards and happy new year ,

Walid Touijri

________________________________

**Comment by luispedro** [comment]
@touijri You can use this Q&A for more general, open-ended, discussions:

http://twotoreal.com/u/wr/5/building-machine-learning-systems-with-python-second-edition/

**Comment by edvbb** [comment]
Or maybe i don't fully understand
I mean there are movie features (genres, actors, etc...) & user fetures (age, gender, etc....). 
You don't use these features in your models, am I right?

**Comment by luispedro** [comment]
@edvbb : Now, I see what you mean.

You are correct. We do not use these. Indeed, they may help, but, IIRC, the naive approaches are not as helpful as one would hope.

I'm going to close this as an issue here as it is not a "bug" per se, but feel free to move the discussion to twotoreal (see link above).

**Comment by edvbb** [comment]
@luispedro i get Server Error (500) trying to regist :(
and with truing to sign in  i get "This account is inactive."
please, help to regist

**Comment by wrichert** [comment]
@edvbb For me it worked just fine. Can you try again? Also, which account name did you try to register?

**Comment by edvbb** [comment]
@wrichert please check it
edvb & edvbb
i tryed two times

**Comment by wrichert** [comment]
Ok, mail issues have been resolved. You can try to register. Thanks for the patience and sorry for the inconvenience!

**Comment by edvbb** [comment]
@wrichert yes!)
