### ISSUE TITLE
Logic error in code

### ISSUE THREAD

**Issue by Atulkmr** [luispedro/BuildingMachineLearningSystemsWithPython#22]
@luispedro This code on line 88 of Ch01/analyze_webstats.py (and page 22 in the book)
```python
xa = x[:inflection]
ya = y[:inflection]
xb = x[inflection:]
yb = y[inflection:]
```

Since you trimmed the list on line 22, so the values corresponding to some indexes have been removed.
For example, x[2] has been trimmed out in line 22, and more, this leads to left shift in the values contained in the list. What I mean by that is that now that for  `x[inflection-1]` will contain a value which is actually larger than `inflection`. This division would have worked fine for the raw untrimmed array but not after it's been trimmed. 

Please fix this in the next edition or if I'm wrong then please make me understand how is this correct.

**Comment by Atulkmr** [comment]
A naive fix for this could be 
```python
from bisect import bisect_left

inflection = 3.5*7*24
index_xa = bisect_left(x,inflection,0,len(x))
xa  =  x[:index_xa]
ya  =  y[:index_xa]
xb  =  x[index_xa:]
yb  =  x[index_xa:]
```
This should do what you intended.

**Comment by luispedro** [comment]
Wrongly closed. Sorry.

**Comment by Atulkmr** [comment]
@luispedro did you get the issue ? I'm not sure if I explained it clearly.

**Comment by luispedro** [comment]
@wrichert : any thoughts?
