### ISSUE TITLE
Chapter 2: Issue with threshold.py

### ISSUE THREAD

**Issue by prasunran** [luispedro/BuildingMachineLearningSystemsWithPython#8]
Hi Luis,

I have just started following the book for getting started with machine learning. However, the below code in threshold.py yields a boolean value and not a numpy array on which mean can be calculated.

![image](https://cloud.githubusercontent.com/assets/4341973/7040057/bc4c139c-dde7-11e4-8813-e72358ad8601.png)

**Comment by luispedro** [comment]
Thanks for the message. I can imagine this happening if `fit_model` is called with unexpected arguments, but should work if called correctly. For example, it is used in `seeds_threshold.py` and it works on my side.

Can you please post a full example that triggers the error for you?

**Comment by prasunran** [comment]
Thanks for pointing in the right direction. What I had failed to notice earlier was that after calling the function, the arrays, `pred` and `labels` were having different lengths which was yielding a single boolean value. In fact, this is the case that is happening in the code snippet contained in `chapter.py` at the below location:

![image](https://cloud.githubusercontent.com/assets/4341973/7054110/f7668528-de57-11e4-9d74-30fd7d697d57.png)

Here, `pred` is a boolean array of length 100 whereas `is_virginica` is a boolean array of length 150 which is generating a single bool value. In my opinion, we should add one more line after building `is_virginica` as below to select non-setosa labels only as we are using only non-setosa features:

    is_virginica = is_virginica[~is_setosa]

**Comment by luispedro** [comment]
Is this line 69 in the current (second edition) version of `chapter.py`? If so, it runs correctly on my side.

Note that `is_virginica` is defined as `is_virginica = (labels == 'virginica')` *after* `labels = labels[~is_setosa]`.

If you are using the first edition, I do remember that there were a few of these manipulations which were (unfortunately) not in the book.

**Comment by prasunran** [comment]
Unfotunately, I am using the first edition of the book. However, I am now able to execute the code without any errors. Thanks for all your support.

**Comment by luispedro** [comment]
Great that you solved your problem.

The code related updates to the book are all in this repository, so if you run into any issues, check here or get in touch (we're always happy to help).
